plugins {
    alias(libs.plugins.android.library)
    /*发布*/
    id 'maven-publish'
}

/*发布*/
group = "io.github.snpmyn"
version = "1.0.0"

android {
    // 编译期用
    // 和 APK 安装无关
    // 可统一用一个 namespace
    // 主要影响生成的 R 类和 BuildConfig 包名
    namespace 'com.zsp.core'
    compileSdk rootProject.ext.compileSdk

    defaultConfig {
        minSdk rootProject.ext.minSdk

        // consumer-rules.pro 会合并到最终 APK
        // consumer-rules.pro 专门用于传递给主应用 (消费者)。它指定的规则是确保主应用在混淆时，能正确处理这个库的代码。这些规则会被打包到 AAR 中。
        // proguard-rules.pro 仅用于当前 Library 自身构建时的混淆
        // proguard-rules.pro 不会自动传递给引用它的 App
        consumerProguardFiles "consumer-rules.pro"
    }

    compileOptions {
        // 源代码兼容 Java 11 (可按需设)
        sourceCompatibility rootProject.ext.sourceCompatibility
        // 生成的字节码兼容 Java 11 (可按需设)
        targetCompatibility rootProject.ext.targetCompatibility
    }
    kotlin {
        compilerOptions {
            jvmTarget.set(rootProject.ext.jvmTarget)
        }
    }

    /*发布*/
    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
}

dependencies {
    api libs.appcompat
    api libs.material
    api libs.constraintlayout
    /*自带*/
    api libs.core.ktx
    /*kotlin*/
    api libs.jxl
    api libs.ion
    api libs.mpac
    api libs.mmkv
    api libs.lunar
    api libs.glide
    api libs.timber
    api libs.rxjava
    api libs.lottie
    api libs.palette
    api libs.relinker
    api libs.retrofit
    api libs.eventbus
    api libs.rxandroid
    api libs.preference
    debugApi libs.glance
    api libs.permissionx
    api libs.work.runtime
    api project(':youmeng')
    api libs.converter.gson
    api libs.rxjava3.rxjava
    api libs.rxjava3.rxandroid
    /*api libs.tensorflow.lite*/
    api libs.localbroadcastmanager
    /*api files('libs/TarsosDSP-Android-2.4.jar')*/
    api libs.material3
    api libs.activity.compose
    api libs.ui
    debugApi libs.ui.tooling
    api libs.ui.tooling.preview
    /*compose*/
    api libs.lifecycle.livedata.ktx
    /*LiveData*/
    api libs.lifecycle.viewmodel.ktx
    /*ViewModel*/
}

/*发布*/
publishing {
    publications {
        release(MavenPublication) {
            groupId = project.group
            artifactId = "core"
            version = project.version

            afterEvaluate {
                from components.release
            }

            pom {
                name = "core"
                description = "Today Android Core Library"
                url = "https://github.com/snpmyn/Today"

                licenses {
                    license {
                        name = "Apache License, Version 2.0"
                        url = "https://www.apache.org/licenses/LICENSE-2.0.txt"
                    }
                }

                developers {
                    developer {
                        id = "snpmyn"
                        name = "snpmyn"
                        /*email = "snpmyn@126.com"*/
                    }
                }

                scm {
                    connection = "scm:git:https://github.com/snpmyn/Today.git"
                    developerConnection = "scm:git:ssh://git@github.com:snpmyn/Today.git"
                    url = "https://github.com/snpmyn/Today"
                }
            }
        }
    }

    repositories {
        // 本地测试仓库
        maven {
            name = "localTest"
            url = layout.buildDirectory.dir("repo")
        }

        // 如果以后发 Nexus
        /*
        maven {
            name = "nexus"
            url = uri("https://nexus.xxx.com/repository/releases")

            credentials {
                username = nexusUser
                password = nexusPassword
            }
        }
        */
    }
}

/*本地 Maven 仓库*/
/*./gradlew :core:publishToMavenLocal*/
/*依赖*/
/*implementation "io.github.snpmyn:core:1.0.0"*/
/*路径*/
/*~/.m2/repository/io/github/snpmyn/core/1.0.0/*/